<a href="https://colab.research.google.com/github/kadayatkushal/TensorFlow_Ai/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [ ]:
df=pd.read_csv("stock.csv")

In [ ]:
df.head(2)

Symbol        Date     Open     High      Low    Close Percent Change  \
0  NEPSE  2025-01-02  2583.94  2586.23  2566.27  2586.23         0.17 %   
1  NEPSE  2025-01-01  2577.43  2589.42  2567.97  2581.60         0.19 %   

             Volume  
0  4,603,282,379.17  
1  3,597,445,334.37

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1112 entries, 0 to 1111
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   Symbol          1112 non-null   object        
 1   Date            1112 non-null   datetime64[ns]
 2   Open            1112 non-null   float64       
 3   High            1112 non-null   float64       
 4   Low             1112 non-null   float64       
 5   Close           1112 non-null   float64       
 6   Percent Change  1112 non-null   object        
 7   Volume          1112 non-null   object        
dtypes: datetime64[ns](1), float64(4), object(3)
memory usage: 69.6+ KB


In [ ]:
df['Close']

0       0.695465
1       0.693161
2       0.690623
3       0.707085
4       0.717600
          ...   
1107    0.058448
1108    0.055696
1109    0.043782
1110    0.054128
1111    0.062065
Name: Close, Length: 1112, dtype: float64

In [ ]:
scaler = MinMaxScaler (feature_range=(0,1))
df['Close'] = scaler.fit_transform(df[['Close']])

In [ ]:
df

Symbol       Date     Open     High      Low     Close Percent Change  \
0     NEPSE 2025-01-02  2583.94  2586.23  2566.27  0.695465         0.17 %   
1     NEPSE 2025-01-01  2577.43  2589.42  2567.97  0.693161         0.19 %   
2     NEPSE 2024-12-31  2613.70  2613.95  2545.34  0.690623        -1.26 %   
3     NEPSE 2024-12-29  2631.98  2641.17  2601.84  0.707085        -0.80 %   
4     NEPSE 2024-12-26  2625.44  2639.08  2607.75  0.717600         0.15 %   
...     ...        ...      ...      ...      ...       ...            ...   
1107  NEPSE 2020-01-28  1300.65  1316.44  1300.65  0.058448         0.00 %   
1108  NEPSE 2020-01-27  1276.68  1300.62  1274.03  0.055696         0.00 %   
1109  NEPSE 2020-01-26  1298.67  1299.46  1275.52  0.043782         0.00 %   
1110  NEPSE 2020-01-23  1314.16  1320.76  1295.80  0.054128         0.00 %   
1111  NEPSE 2020-01-22  1324.32  1325.69  1310.64  0.062065         0.00 %   

                Volume  
0     4,603,282,379.17  
1     3,597,445,334.37  
2     5,674,686,091.49  
3     5,474,868,764.77  
4     5,329,274,454.77  
...                ...  
1107  1,400,467,805.00  
1108    917,359,865.00  
1109    965,018,662.00  
1110  1,384,209,412.00  
1111  1,581,381,364.00  

[1112 rows x 8 columns]

In [ ]:
df = df[['Date', 'Close']]

In [ ]:
scaler = MinMaxScaler (feature_range=(0,1))
df['Close'] = scaler.fit_transform(df[['Close']])

In [ ]:
df

Date     Close
0    2025-01-02  0.695465
1    2025-01-01  0.693161
2    2024-12-31  0.690623
3    2024-12-29  0.707085
4    2024-12-26  0.717600
...         ...       ...
1107 2020-01-28  0.058448
1108 2020-01-27  0.055696
1109 2020-01-26  0.043782
1110 2020-01-23  0.054128
1111 2020-01-22  0.062065

[1112 rows x 2 columns]

In [ ]:
close_prices = df['Close'].values.reshape(-1,1)

In [ ]:
close_prices

array([[0.69546502],
       [0.69316095],
       [0.69062299],
       ...,
       [0.04378225],
       [0.05412816],
       [0.0620655 ]])

In [ ]:
seq_length=5
i=1
close_prices[i:i+seq_length]

array([[0.69316095],
       [0.69062299],
       [0.70708488],
       [0.71759999],
       [0.71541038]])

In [ ]:
def create_sequences(data, seq_length):
  sequences = []
  labels = []

  for i in range(len(data) - seq_length):
    sequences.append(data[i:i+seq_length])
    labels.append(data[i+seq_length])

  return np.array(sequences), np.array(labels)


In [ ]:
seq_length = 3
X,y = create_sequences(close_prices, seq_length)
X,y

(array([[[0.69546502],
         [0.69316095],
         [0.69062299]],
 
        [[0.69316095],
         [0.69062299],
         [0.70708488]],
 
        [[0.69062299],
         [0.70708488],
         [0.71759999]],
 
        ...,
 
        [[0.0583133 ],
         [0.05844767],
         [0.05569572]],
 
        [[0.05844767],
         [0.05569572],
         [0.04378225]],
 
        [[0.05569572],
         [0.04378225],
         [0.05412816]]]),
 array([[0.70708488],
        [0.71759999],
        [0.71541038],
        ...,
        [0.04378225],
        [0.05412816],
        [0.0620655 ]]))

In [ ]:
X.shape

(1109, 3, 1)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(887, 3, 1)

In [ ]:
y.shape

(1109, 1)

In [ ]:
model = Sequential([
    LSTM(50, input_shape=(X_train.shape[1], 1), return_sequences=True),
    LSTM(50, return_sequences=False),
    Dense(1)
])
model.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
model.fit(X_train, y_train, epochs=100, batch_size=32)
predictions = model.predict(X_test)
predictions = scaler.inverse_transform(predictions)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1,1))
print(f"Predicted: {predictions[5]}")
print(f"Actual: {y_test_actual[5]}")


Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.2165
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0176
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060
Epoch 4/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0023
Epoch 5/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0010
Epoch 6/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.5866e-04
Epoch 7/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.6880e-04
Epoch 8/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7952e-04
Epoch 9/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.7497e-04
Epoch 10/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.8800e-04
Epoch 11/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.4569e-04
Epoch 12/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0961e-04
Epoch 13/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8935e-04
Epoch 14/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5312e-04
Epoch 15/100
28/28 ━━━━━━━━━━━━━━━